server:
  port: 8766
spring:
  application:
    name: consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/


logging:
  config: conf/logback/${spring.application.name}-logback.xml
